version: '3'

services:
  nextjs:
    container_name: next-js-test
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    command: "npm start"