name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Copy files via SSH
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no root@125.133.75.11 <<EOF
            cd /web-test
            if [ ! -d ".git" ]; then
              git init
              git remote set-url origin https://htm-FX707ZV4:$PAT_TOKEN@github.com/work-ethanhuh/next-js-test.git
            fi
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          EOF
